### ISSUE TITLE
How about add a book named DDIA(《Designing Data-Intensive Application》)?

### ISSUE THREAD

**Issue by woodpenker** [pingcap/awesome-database-learning#10]
The book shop: http://shop.oreilly.com/product/0636920032175.do
Here is the CN Translate version on GitHub: https://github.com/Vonng/ddia

**Comment by zz-jason** [comment]
Sure! Would you like to be a contributor of this repo by filing a PR to put it into the [Books](https://github.com/pingcap/awesome-database-learning#books) section?
