### ISSUE TITLE
Video links?

### ISSUE THREAD

**Issue by evanxg852000** [pingcap/awesome-database-learning#23]
Do we have video links to the talks?

Talks
Data Structures and Algorithms for Big Databases
A Journey From A Quick HackTo A High-Reliability Database Engine

**Comment by zz-jason** [comment]
I'm not sure whether I can find the video. @laixintao, how about you?

**Comment by laixintao** [comment]
Sorry me neither, but I think the slide is pretty clear. :)

**Comment by evanxg852000** [comment]
Closed it as it seems like we have to content ourselves with the slides. I also searched over for the video.
